### ISSUE TITLE
Keyword arguments error on Ruby 3

### ISSUE THREAD

**Issue by Shimokuni** [r7kamura/rack-json_schema#14]
@r7kamura Thank you for this useful software!

Are there any plans to support Ruby 3 with this gem?
For example it does not work here with ruby 3 because Ruby 3.0 separates positional and keyword arguments.

https://github.com/r7kamura/rack-json_schema/blob/4becf4f920d2dc7d54cdba2f337017c669ad2469/lib/rack/json_schema/docs.rb#L37-L52

If I make a PR to fix this, could you review and merge it?

**Comment by r7kamura** [comment]
Thank you for your interest. Yes, if you send me a pull request, I will review it and merge it if it looks good.

I will do my best, but I am not actively using this library at this time, so my response may be a little slow.

**Comment by Shimokuni** [comment]
@r7kamura 
I made PR. Could you review and merge it?
https://github.com/r7kamura/rack-json_schema/pull/15
